#!/bin/bash
until mysql -u root -h 127.0.0.1 -P 33061 --password=secret -e 'SELECT 1' > /dev/null; do
  >&2 echo "MySQL 127.0.0.1:33061 for user root is unavailable - sleeping"
  sleep 1
done
>&2 echo "MySQL 127.0.0.1:33061 is up"