version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: ./web.docker
        image: jarvvski/nginx:dev
        depends_on:
            - db
            - cache
        container_name: nginx
        volumes:
            - ./:/srv/www
        ports:
            - "80:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: ./app.docker
        image: jarvvski/charlog:dev
        container_name: php
        volumes:
            - ./:/srv/www
        depends_on:
            - db
        links:
            - db
            - cache
        environment:
            - "DB_HOST=db"
            - "DB_PORT=3306"
            - "DB_DATABASE=Charlog"
            - "DB_USERNAME=root"
            - "DB_PASSWORD=secret"
            - "REDIS_HOST=cache"
            - "REDIS_PORT=6379"

    db:
        image: mysql:5.7
        container_name: db
        restart: always
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=Charlog"
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "33061:3306"

    cache:
        image: redis:3.0
        container_name: cache
        ports:
            - "6379:6379"

volumes:
    db_data:
